name: compile
run-name: ${{ github.actor }}'s rust compile
on: workflow_dispatch
jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: rust_grade
            name: precious-FreeBSD-x86_64.tar.gz
            command: build
            path: /project

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: rust_grade.exe
            name: precious-Windows-x86_64.zip
            command: both
            path: D:\a\rust\rust

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: rust_grade
            name: precious-Darwin-x86_64.tar.gz
            command: both
            path: /Users/runner/work/rust/rust

            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Get Binaries
        uses: edwardgeorge/file-outputs-action@main
        with:
          files: binary_${{ matrix.platform.release_for }}=${{ matrix.platform.path }}/${{ matrix.platform.bin }}

